# this file is for the local server

http:
  # @todo change the default port?
  port: 8000
  allow_http: true # Prevent auto-redirection from HTTP to HTTPS
  #daemon: true # Run the server in the background
  use_gzip: true # Toggle GZIP compression
  # @todo change this to false when the local server is correctly installed
  no_tls: true # Use HTTP instead of HTTPS

