<?php

declare(strict_types=1);

namespace App; 

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        date_default_timezone_set(
            timezoneId: $this->container->getParameter('app.timezone'),
        );
    }
}
